/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package garden.ephemeral.gradle.warnings

import assertk.all
import assertk.assertThat
import assertk.assertions.contains
import assertk.assertions.isEqualTo
import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

/**
 * A simple functional test for the 'garden.ephemeral.gradle.warnings.greeting' plugin.
 */
class GradleWarningsPluginFunctionalTest {

    @TempDir
    lateinit var projectDir: File

    @Test
    fun `task runs and produces the expected report`() {
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('java')
                id('garden.ephemeral.warnings')
            }
            tasks.compileJava {
                options.compilerArgs << '-Xlint'
            }
        """)
        projectDir.resolve("src/main/java").mkdirs()
        projectDir.resolve("src/main/java/Blah.java").writeText("""
            import java.util.ArrayList;
            import java.util.List;
            public class Blah {
                private List<String> fish = (List<String>) new ArrayList();
            }
        """.trimIndent())

        val result = GradleRunner.create()
            // Useful for diagnosing issues:
            //.forwardOutput()
            .withPluginClasspath()
            .withArguments("warningsReport")
            .withProjectDir(projectDir)
            .build()

        assertThat(result.task(":warningsReport")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)

        val report = projectDir.resolve("build/reports/warnings/report.html").readText()
        assertThat(report).all {
            contains("<p>Total warnings: <strong>2</strong></p>")
            contains("<td><a href=\"#warning/rawtypes\">warning/rawtypes</a></td>")
            contains("<table id=\"warning/rawtypes\">")
            contains("<td>src/main/java/Blah.java:4</td>")
        }
    }
}
